### ISSUE TITLE
Bouncing not work for Cupertino

### ISSUE THREAD

**Issue by Kiruel** [idootop/nested_scroll_view_plus#1]
First of all thanks to trying to fix NestedScrollView ! It's a pain to use with to many issues on it.

So my problem is when I use it with a `CupertinoSliverNavigationBar` the equivalent of `SliverAppBar` the bouncing do not work.

The bouncing work on the end of the list but not on the header. So my "Title" do not animate with the scroll.

I'm using `SliverList.separated` inside the `CustomScrollView`. Maybe it's related ?

**Comment by idootop** [comment]
Thank you for your question. I haven't used `CupertinoSliverNavigationBar`.

Could you please provide a minimal reproducible code example and a screen recording to demonstrate the problem?

**Comment by Kiruel** [comment]
When I got some time I will make you an example. It's a complex view with search part and tabs view part, all with Cupertino widgets and sliver.

**Comment by Kiruel** [comment]
Was removed   `ScrollPhysics? physics` from the`NestedScrollViewPlus` and now it works ! Closing the issue.
