### ISSUE TITLE
webview 不兼容

### ISSUE THREAD

**Issue by cjnwan** [idootop/nested_scroll_view_plus#10]
下面是一个 wbeview的话，webview无法滚动到最底部，无法根据内容撑开高度

**Comment by idootop** [comment]
> 无法根据内容撑开高度

跟嵌套列表有关系，本身内部的列表并不是 expand 外部容器剩余可用空间的。

你可能需要自己手动计算指定 webview 包裹容器的实际高度。

这是一个 Flutter 组件的布局问题，与此库无关。
