### ISSUE TITLE
如何在顶部添加下拉刷新

### ISSUE THREAD

**Issue by cjnwan** [idootop/nested_scroll_view_plus#8]

**Comment by idootop** [comment]
参考这个项目：https://github.com/idootop/scroll_master

**Comment by cjnwan** [comment]
> 参考这个项目：https://github.com/idootop/scroll_master

是要自己实现下拉刷新嘛，三方的 pulltorefresh不支持嘛

**Comment by idootop** [comment]
没试过，建议自己实现一个
