### ISSUE TITLE
flutter3.13.6 版本运行报错， 找不到ChangeNotifier.maybeDispatchObjectCreation，请注明库版本和flutter版本的对应关系

### ISSUE THREAD

**Issue by philos3** [idootop/nested_scroll_view_plus#9]
Running Gradle task 'assembleDebug'...
../../../.pub-cache/hosted/pub.flutter-io.cn/nested_scroll_view_plus-2.0.0/lib/src/nested_scroll_view.dart:1693:22: Error: Member not found: 'ChangeNotifier.maybeDispatchObjectCreation'.
      ChangeNotifier.maybeDispatchObjectCreation(this);
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by philos3** [comment]
<img width="881" alt="image" src="https://github.com/user-attachments/assets/80dec946-1436-4206-955c-86109dab15b9">
 flutter3.13.6 对应dart版本 3.1.3 是满足你的这个最小版本要求的

**Comment by idootop** [comment]
多谢反馈，我稍后更新一下

**Comment by idootop** [comment]
@philos3  你的 Flutter 版本的问题，有几个小版本官方多加了一些有兼容性问题的代码，这些存在问题的代码在后续的版本中已经 revoke 了，仅存在于个别 Flutter master/beta 版本中，建议升级到 `Flutter 3.19.0` 及以上。
